name: CICD

on:
  push: 
    branches: [main]
        
jobs: 
  generate-version:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4.1.1
        
      - name: GitHub Tag Bump
        uses: anothrNick/github-tag-action@1.67.0
        id: tag_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          
    outputs: 
      new_version: ${{ steps.tag_bump.outputs.new_tag }}
    
  package-and-publish-contracts:
    
    runs-on: ubuntu-latest
    needs: generate-version
    
    steps:
      - uses: actions/checkout@v4.1.1
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pack
        run: |
          dotnet pack SomeLIb/SomeLIb.csproj \
          -c Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
          -p:RepositoryUrl=https://github.com/${{ github.repository_owner }}/NugetPublishTest \
          -o packages
          
      - name: Publish
        run: dotnet nuget push packages/*.nupkg
      
#name: Continues Deployment
#
#on:
#  workflow_dispatch: 
#    
#jobs: 
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: 8.0.x
#      - name: Pack
#        run: dotnet pack ./SomeLIb/SomeLIb.csproj -c Release
#      - name: Upload NuGet package to GitHub
#        uses: actions/upload-artifact@v2
#        with:
#          name: nugetPackage
#          path: ./SomeLIb/bin/Release/
#          
#  release:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    needs: build
#    steps:
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: 8.0.x
#          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
#        env:
#          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Download NuGet package artifact
#        uses: actions/download-artifact@v1.0.0
#        with:
#          name: nugetPackage
#      - name: Publish to GitHub Packages
#        run: dotnet nuget push nugetPackage/*.nupkg