name: Continues Deployment

on:
  workflow_dispatch: 
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack ./SomeLIb/SomeLIb.csproj -c Release
      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: nugetPackage
          path: ./SomeLIb/bin/Release/
          
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: nugetPackage
      - name: Prep package
        run: dotnet nuget add source --username bmartens88 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bmartens88/index.json"
      - name: Publish to GitHub Packages
        run: dotnet nuget push nugetPackage/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"