name: Continues Deployment

on:
  workflow_dispatch: 
    
jobs: 
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Pack
        run: dotnet pack .\SomeLIb\SomeLIb.csproj -c Release
      - name: Prep package
        run: dotnet nuget add source --username bmartens88 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bmartens88/index.json"
      - name: Publish to GitHub Packages
        run: dotnet nuget push .\SomeLIb\bin\Release\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"